baseURL = "https://example.com"
languageCode = "en-us"
title = "callesp"
theme = "mini"

defaultContentLanguage = "en"
hasCJKLanguage = true
paginate = 3
googleAnalytics = "your-google-analytics-id"
disqusShortname = "your-disqus-shortname"

[permalinks]
posts = "/posts/:title/"

[markup.highlight]
guessSyntax = true
style = "emacs"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

[social]
github = "https://github.com/callesp"
#twitter = "your-github-link"
#stackoverflow = "your-github-link"

[params]
author = "Author"
bio = "Software Engineer"
description = "My Blog"
enableRSS = true
enableComments = true
enableGoogleAnalytics = true
showToc = true
showPowerBy = true
math = false
hiddenPostSummaryInHomePage = false
copyright = ""
